services:
  - type: web
    name: car-service-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
